[build]
  command = "jekyll build --trace"
  publish = "_site"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://xplnai.com;
      style-src 'self' 'unsafe-inline' https://xplnai.com https://fonts.googleapis.com;
      frame-src 'self' https://xplnai.com;
      connect-src 'self' https://*.xplnai.com;
      font-src 'self' https://fonts.gstatic.com;
    """